### ISSUE TITLE
Kindly help me 

### ISSUE THREAD

**Issue by Aakasha01Agarwal** [ksingh25/SwitchTree#3]
I want to write my own randomforest.p4 file for classification on [this](https://iotanalytics.unsw.edu.au/iottraces) dataset. I am using three features (Protocol, ipv4.src and ipv4.dst). How should I proceed, I already have trained the model in python.

**Comment by ksingh25** [comment]
Hello,

I think perhaps first try to test and understand switchtree.p4
After that you will have to add these features (feature 13, 14, 15) and modify action CheckFeature and design the rules to be uploaded to the tables.
Note that these 3 features dont need to be stored in registers as they are already present in the header or metadata. Your randomforest.p4 will be much simpler. 

by the way, I am not sure if src, dst and protocol are reliable enough to classify IoT data.

**Comment by Aakasha01Agarwal** [comment]
Thank you so much for the reply. I am sorry if you find my questions silly. I am very new to p4 programming and Networking in general. Could you please tell me in what sense I have to modify the Checkfeature? 


I get your point that these features might not be reliable enough, but right now my main focus is to get a very basic .p4 program. I can always do manipulations in the machine learning side as I am comfortable with that. 

Thank you for the quick response sir, I am again very sorry if my questions seem very naïve to you

**Comment by Aakasha01Agarwal** [comment]
Could you tell me what kind of values do I need to add in the rules. Like in your [rftop4_v2.py](https://github.com/ksingh25/SwitchTree/blob/master/scripts/rftop4_v2.py) file you have created previous feature, previous_id, current_id and classname for SetClass and threshold for Checkfeature.  
I think I just need the class name and the threshold. Am I right?

**Comment by ksingh25** [comment]
Hello,
You should check the paper: https://hal.archives-ouvertes.fr/hal-02968593/document.

For example section 4.1 describes node id, previous feature id etc.
Example rules look like the following.
table_add MyIngress.level1 MyIngress.CheckFeature 0 0 1 => 1 9 20000
table_add MyIngress.level2 MyIngress.CheckFeature 1 9 1 => 2 4 0
table_add MyIngress.level3 MyIngress.CheckFeature 2 4 1 => 3 1 1

It corresponds to one branch of the following tree. It is saying on node 1 if feature 9 was less than equal to 20000 (0.02 in the tree) then result = 1 (in P4 program meta.isTrue = 1)

Next time in rule it will match the key 1 9 1 (node id , feature id, isTrue)
Thus,  it will match and will go to node 2 and check for feature 4 with 0 as threshold (it is binary so <= 0 is equivalent to <=0.50) 

In case it was more than 20000 then it will match another rule and will check feature 2:
table_add MyIngress.level2 MyIngress.CheckFeature 1 9 0 => 99 2 156

Here is the tree in the above example from the scripts folder:
TREE  0
|--- feature_9 <= 0.02
|   |--- feature_4 <= 0.50
|   |   |--- feature_1 <= 1.00
...
...
|--- feature_9 >  0.02
|   |--- feature_2 <= 156.00

For your program, you may just create a new feature id for your features. Think of adding rules for them and then add the check in the end of the checkfeature.

**Comment by Aakasha01Agarwal** [comment]
Thank you so much @ksingh25. This helped me a lot.
